// ─── Albums data ────────────────────────────────────────────────────────────
// Audio files are served from /public/audio/<album-id>/<filename>.mp3
// Cover images are served from /public/covers/<filename>

export const albums = [
  {
    id: "gaj",
    title: "Good Ass Job",
    artist: "Kanye West",
    year: "2010",
    genre: "Hip-Hop",
    cover: "/covers/good-ass-job-cover.jpg",
    tracks: [
      { title: "Crazy Life", src: "/audio/good-ass-job/crazy-life.mp3" },
      { title: "Downtown", src: "/audio/good-ass-job/downtown.mp3" },
      { title: "Eyes Closed", src: "/audio/good-ass-job/eyes-closed.mp3" },
      { title: "Flashing Lights 2", src: "/audio/good-ass-job/flashing-lights-2.mp3" },
      { title: "Ghetto University", src: "/audio/good-ass-job/ghetto-university.mp3" },
      { title: "Flight School", src: "/audio/good-ass-job/flight-school.mp3" },
      { title: "Gorgeous", src: "/audio/good-ass-job/gorgeous.mp3" },
      { title: "Hard Horn Nightmare", src: "/audio/good-ass-job/hard-horn-nightmare.mp3" },
      { title: "Heartbreaker", src: "/audio/good-ass-job/heartbreaker.mp3" },
      { title: "Hell Of A Life", src: "/audio/good-ass-job/hell-of-a-life.mp3" },
      { title: "Higher", src: "/audio/good-ass-job/higher.mp3" },
      { title: "Holding Me Back", src: "/audio/good-ass-job/holding-me-back.mp3" },
      { title: "I'll Be Alright", src: "/audio/good-ass-job/ill-be-alright.mp3" },
      { title: "Ice Cube", src: "/audio/good-ass-job/ice-cube.mp3" },
      { title: "Take One For The Team", src: "/audio/good-ass-job/take-one-for-the-team.mp3" },
      { title: "Lonely", src: "/audio/good-ass-job/lonely.mp3" },
      { title: "Lost In The World", src: "/audio/good-ass-job/lost-in-the-world.mp3" },
      { title: "Mama's Boy", src: "/audio/good-ass-job/mamas-boy.mp3" },
      { title: "Never See Me Again", src: "/audio/good-ass-job/never-see-me-again.mp3" },
      { title: "No Parties In LA", src: "/audio/good-ass-job/no-parties-in-la.mp3" },
      { title: "POWER", src: "/audio/good-ass-job/power.mp3" },
      { title: "Runaway", src: "/audio/good-ass-job/runaway.mp3" },
      { title: "White Dress", src: "/audio/good-ass-job/white-dress.mp3" },
      { title: "Shoot Up The Station", src: "/audio/good-ass-job/shoot-up-the-station.mp3" },
      { title: "So Apalled", src: "/audio/good-ass-job/so-apalled.mp3" },
      { title: "Supernova", src: "/audio/good-ass-job/supernova.mp3" },
      { title: "Sweat On My Face", src: "/audio/good-ass-job/sweat-on-my-face.mp3" },
      { title: "The Joy", src: "/audio/good-ass-job/the-joy.mp3" },
      { title: "Throw Money Everywhere", src: "/audio/good-ass-job/throw-money-everywhere.mp3" },
      { title: "★ Monster", src: "/audio/good-ass-job/monster.mp3", bonus: true },
      { title: "★ That's My Bitch", src: "/audio/good-ass-job/thats-my-bitch.mp3", bonus: true },
      {
        title: "★ Only For The Night",
        src: "/audio/good-ass-job/only-for-the-night.mp3",
        bonus: true,
      },
    ],
  },
  {
    id: "tgfd",
    title: "Thank God For Drugs",
    artist: "Kanye West",
    year: "2012",
    genre: "Hip-Hop",
    cover: "/covers/tgfd.gif",
    tracks: [
      { title: "I Am Not Home", src: "/audio/thank-god-for-drugs/i-am-not-home.mp3" },
      { title: "Yeezus", src: "/audio/thank-god-for-drugs/yeezus.mp3" },
      { title: "Send It Up", src: "/audio/thank-god-for-drugs/send-it-up.mp3" },
      { title: "Can't Get Over Me", src: "/audio/thank-god-for-drugs/cant-get-over-me.mp3" },
      { title: "Talk To Me", src: "/audio/thank-god-for-drugs/talk-to-me.mp3" },
      { title: "LOUDER", src: "/audio/thank-god-for-drugs/louder.mp3" },
      {
        title: "Good Things Don't Last",
        src: "/audio/thank-god-for-drugs/good-things-dont-last.mp3",
      },
      { title: "Perfect Bitch", src: "/audio/thank-god-for-drugs/perfect-bitch.mp3" },
      { title: "Blood On The Leaves", src: "/audio/thank-god-for-drugs/blood-on-the-leaves.mp3" },
      { title: "On Site", src: "/audio/thank-god-for-drugs/on-site.mp3" },
      { title: "GOD", src: "/audio/thank-god-for-drugs/god.mp3" },
      { title: "Guilt Trip", src: "/audio/thank-god-for-drugs/guilt-trip.mp3" },
      { title: "New Slaves", src: "/audio/thank-god-for-drugs/new-slaves.mp3" },
      { title: "Black Skinhead", src: "/audio/thank-god-for-drugs/black-skinhead.mp3" },
      { title: "Emotionless", src: "/audio/thank-god-for-drugs/emotionless.mp3" },
      { title: "No No No No", src: "/audio/thank-god-for-drugs/no-no-no-no.mp3" },
      { title: "Hollywood", src: "/audio/thank-god-for-drugs/hollywood.mp3" },
      { title: "Awesome", src: "/audio/thank-god-for-drugs/awesome.mp3" },
      { title: "One I Love", src: "/audio/thank-god-for-drugs/one-i-love.mp3" },
      { title: "Nobody To Love", src: "/audio/thank-god-for-drugs/nobody-to-love.mp3" },
    ],
  },
  {
    id: "yeezus2",
    title: "Yeezus 2",
    artist: "Kanye West",
    year: "2013",
    genre: "Hip-Hop / Electronic",
    cover: "/covers/yeezus-2.gif",
    tracks: [
      { title: "The World", src: "/audio/yeezus-2/the-world.mp3" },
      { title: "So Special", src: "/audio/yeezus-2/so-special.mp3" },
      { title: "Black Skinhead (Remix)", src: "/audio/yeezus-2/black-skinhead-remix.mp3" },
      { title: "Back Up Off The Ledge", src: "/audio/yeezus-2/back-up-off-the-ledge.mp3" },
      { title: "Bad Night", src: "/audio/yeezus-2/bad-night.mp3" },
      { title: "Gut Feeling", src: "/audio/yeezus-2/gut-feeling.mp3" },
      { title: "I Can't Let Go", src: "/audio/yeezus-2/i-cant-let-go.mp3" },
      { title: "Never Let Me Go", src: "/audio/yeezus-2/never-let-me-go.mp3" },
      { title: "NinaChop", src: "/audio/yeezus-2/ninachop.mp3" },
      { title: "Tom Cruise", src: "/audio/yeezus-2/tom-cruise.mp3" },
      { title: "When I See It", src: "/audio/yeezus-2/when-i-see-it.mp3" },
      { title: "New Angels", src: "/audio/yeezus-2/new-angels.mp3" },
      { title: "Mrs. Misery", src: "/audio/yeezus-2/mrs-misery.mp3" },
      { title: "Crosses", src: "/audio/yeezus-2/crosses.mp3" },
      { title: "God Level", src: "/audio/yeezus-2/god-level.mp3" },
      { title: "Creep Theme", src: "/audio/yeezus-2/creep-theme.mp3" },
      { title: "Piss On Your Grave", src: "/audio/yeezus-2/piss-on-your-grave.mp3" },
      { title: "I Been Trill", src: "/audio/yeezus-2/i-been-trill.mp3" },
      { title: "Hummer", src: "/audio/yeezus-2/hummer.mp3" },
      { title: "You Ain't No Model", src: "/audio/yeezus-2/you-aint-no-model.mp3" },
      { title: "Fall Into You", src: "/audio/yeezus-2/fall-into-you.mp3" },
      { title: "After You", src: "/audio/yeezus-2/after-you.mp3" },
      { title: "So Crazy", src: "/audio/yeezus-2/so-crazy.mp3" },
      {
        title: "★ Father Stretch My Hands",
        src: "/audio/yeezus-2/fsmh.mp3",
        bonus: true,
      },
    ],
  },
  {
    id: "yandhi",
    title: "Yandhi",
    artist: "Kanye West",
    year: "2018",
    genre: "Hip-Hop / R&B",
    cover: "/covers/yandhi.gif",
    tracks: [
      { title: "Chakras", src: "/audio/yandhi/chakras.mp3" },
      { title: "Calm (Interlude)", src: "/audio/yandhi/calm.mp3" },
      { title: "The Storm", src: "/audio/yandhi/the-storm.mp3" },
      { title: "Spread Your Wings", src: "/audio/yandhi/spread-your-wings.mp3" },
      { title: "New Body", src: "/audio/yandhi/new-body.mp3" },
      { title: "80 Degrees", src: "/audio/yandhi/80-degrees.mp3" },
      { title: "Alien (Interlude)", src: "/audio/yandhi/alien-interlude.mp3" },
      { title: "Alien", src: "/audio/yandhi/alien.mp3" },
      { title: "Home", src: "/audio/yandhi/home.mp3" },
      { title: "City In The Sky", src: "/audio/yandhi/city-in-the-sky.mp3" },
      { title: "Brothers", src: "/audio/yandhi/brothers.mp3" },
      { title: "Cash To Burn", src: "/audio/yandhi/cash-to-burn.mp3" },
      { title: "We Got Love", src: "/audio/yandhi/we-got-love.mp3" },
      { title: "All Dreams Real", src: "/audio/yandhi/all-dreams-real.mp3" },
      { title: "The Garden", src: "/audio/yandhi/the-garden.mp3" },
      { title: "Last Name", src: "/audio/yandhi/last-name.mp3" },
      { title: "Law Of Attraction", src: "/audio/yandhi/law-of-attraction.mp3" },
      { title: "End Of It", src: "/audio/yandhi/end-of-it.mp3" },
      { title: "★ Bye Bye Baby", src: "/audio/yandhi/bye-bye-baby.mp3", bonus: true },
      { title: "★ On God", src: "/audio/yandhi/on-god.mp3", bonus: true },
    ],
  },
  {
    id: "sohelpmegod",
    title: "So Help Me God",
    artist: "Kanye West",
    year: "2015",
    genre: "Hip-Hop",
    cover: "/covers/so-help-me-god.jpg",
    tracks: [
      { title: "The World", src: "/audio/so-help-me-god/the-world-2.mp3" },
      { title: "All Day", src: "/audio/so-help-me-god/all-day.mp3" },
      { title: "Tom Cruise", src: "/audio/so-help-me-god/tom-cruise-2.mp3" },
      { title: "Midas Touch", src: "/audio/so-help-me-god/midas-touch.mp3" },
      { title: "Been Trill", src: "/audio/so-help-me-god/been-trill.mp3" },
      { title: "FourFiveSeconds", src: "/audio/so-help-me-god/45seconds.mp3" },
      { title: "Piss On Your Grave", src: "/audio/yeezus-2/piss-on-your-grave.mp3" },
      { title: "Souls", src: "/audio/so-help-me-god/souls.mp3" },
      { title: "Ultimate Lie", src: "/audio/so-help-me-god/ultimate-lie.mp3" },
      { title: "CAN U BE", src: "/audio/so-help-me-god/can-u-be.mp3" },
      { title: "Woke Up", src: "/audio/so-help-me-god/woke-up.mp3" },
      { title: "Prayer", src: "/audio/so-help-me-god/prayer.mp3" },
      { title: "Southside Serenade", src: "/audio/so-help-me-god/southside-serenade.mp3" },
      { title: "Won't Lie", src: "/audio/so-help-me-god/wont-lie.mp3" },
      { title: "Wolves", src: "/audio/so-help-me-god/wolves.mp3" },
      { title: "Sanctified", src: "/audio/so-help-me-god/sanctified.mp3" },
      { title: "When I See It", src: "/audio/yeezus-2/when-i-see-it.mp3" },
      { title: "Only One", src: "/audio/so-help-me-god/only-one.mp3" },
      { title: "I Feel Like That", src: "/audio/so-help-me-god/i-feel-like-that.mp3" },
    ],
  },
  {
    id: "swish",
    title: "SWISH",
    artist: "Kanye West",
    year: "2016",
    genre: "Hip-Hop",
    cover: "/covers/swish.gif",
    tracks: [
      { title: "Nina Chop", src: "/audio/swish/nina-chop.mp3" },
      {
        title: "Father Stretch My Hands Pt. 1",
        src: "/audio/swish/father-stretch-my-hands-pt-1.mp3",
      },
      { title: "Pt. 2", src: "/audio/swish/pt-2.mp3" },
      { title: "Over", src: "/audio/swish/over.mp3" },
      { title: "Forever", src: "/audio/swish/forever.mp3" },
      { title: "Enya", src: "/audio/swish/enya.mp3" },
      { title: "Rich Nigga Drunk", src: "/audio/swish/rich-nigga-drunk.mp3" },
      { title: "Deja Vu", src: "/audio/swish/deja-vu.mp3" },
      { title: "Low Lights", src: "/audio/swish/low-lights.mp3" },
      { title: "Highlights", src: "/audio/swish/highlights.mp3" },
      { title: "High Life", src: "/audio/swish/high-life.mp3" },
      { title: "Facts", src: "/audio/swish/facts.mp3" },
      { title: "30 Hours", src: "/audio/swish/30-hours.mp3" },
      { title: "WE FUCK", src: "/audio/swish/we-fuck.mp3" },
      { title: "No More Parties In LA", src: "/audio/swish/nmpila.mp3" },
      { title: "Internet", src: "/audio/swish/internet-2.mp3" },
      { title: "Fade", src: "/audio/swish/fade.mp3" },
      { title: "Mitus Touch", src: "/audio/swish/mitus-touch.mp3" },
      { title: "FML", src: "/audio/swish/fml.mp3" },
      { title: "Real Friends", src: "/audio/swish/real-friends.mp3" },
      { title: "Wolves", src: "/audio/swish/wolves-2.mp3" },
      { title: "★ Anxiety", src: "/audio/swish/anxiety.mp3", bonus: true },
      { title: "★ Pressure", src: "/audio/swish/pressure.mp3", bonus: true },
      { title: "★ Bad Night", src: "/audio/swish/bad-night-2.mp3", bonus: true },
      { title: "★ Code Red", src: "/audio/swish/code-red.mp3", bonus: true },
      { title: "★ The Mall", src: "/audio/swish/the-mall.mp3", bonus: true },
    ],
  },
  {
    id: "wolves",
    title: "WOLVES",
    artist: "Kanye West",
    year: "2016",
    genre: "Hip-Hop / R&B",
    cover: "/covers/wolves.jpg",
    tracks: [
      { title: "Glow", src: "/audio/wolves/glow.mp3" },
      { title: "Blessings", src: "/audio/wolves/blessings.mp3" },
      { title: "Pop Style", src: "/audio/wolves/pop-style.mp3" },
      { title: "FRIENDFLIP77", src: "/audio/wolves/friendflip77.mp3" },
      { title: "Tell Your Friends", src: "/audio/wolves/tell-your-friends.mp3" },
    ],
  },
  {
    id: "turbografx16",
    title: "TURBOGRAFX16",
    artist: "Kanye West",
    year: "2016",
    genre: "Hip-Hop",
    cover: "/covers/turbografx16.jpg",
    tracks: [
      { title: "ALL EYES ON YE", src: "/audio/turbografx16/all-eyes-on-ye.mp3" },
      { title: "INDIGO INTERLUDE", src: "/audio/turbografx16/indigo-interlude.mp3" },
      { title: "FACE DOWN", src: "/audio/turbografx16/face-down.mp3" },
      { title: "FEEL ME", src: "/audio/turbografx16/feel-me.mp3" },
      { title: "HOLD TIGHT", src: "/audio/turbografx16/hold-tight.mp3" },
      { title: "JEALOUS", src: "/audio/turbografx16/jealous.mp3" },
      { title: "MEDICATED", src: "/audio/turbografx16/medicated.mp3" },
      { title: "CHAMPIONS", src: "/audio/turbografx16/champions.mp3" },
      { title: "EURO", src: "/audio/turbografx16/euro.mp3" },
      { title: "NO REASON", src: "/audio/turbografx16/no-reason.mp3" },
      { title: "RAP TARANTINO", src: "/audio/turbografx16/rap-tarantino.mp3" },
      { title: "ABOVE THE INFLUENCE", src: "/audio/turbografx16/above-the-influence.mp3" },
      { title: "ONLY YE", src: "/audio/turbografx16/only-ye.mp3" },
      { title: "SUPER STARRED", src: "/audio/turbografx16/super-starred.mp3" },
      { title: "WELCOME TO UCLA", src: "/audio/turbografx16/welcome-to-ucla.mp3" },
      { title: "INTERNET", src: "/audio/turbografx16/internet.mp3" },
    ],
  },
  {
    id: "loveeveryone",
    title: "Love Everyone",
    artist: "Kanye West",
    year: "2018",
    genre: "Hip-Hop / Gospel",
    cover: "/covers/jesushelpme.jpg",
    tracks: [
      { title: "I Know I Know", src: "/audio/love-everyone/i-know-i-know.mp3" },
      { title: "Amistad", src: "/audio/love-everyone/amistad.mp3" },
      { title: "Fine Line", src: "/audio/love-everyone/fine-line.mp3" },
      { title: "XCTY", src: "/audio/love-everyone/xcty.mp3" },
      { title: "Take Me To The Lights", src: "/audio/love-everyone/take-me-to-the-lights.mp3" },
      { title: "Brothers (Prologue)", src: "/audio/love-everyone/brothers-prologue.mp3" },
      { title: "Brothers", src: "/audio/love-everyone/brothers-le.mp3" },
      { title: "Lovey", src: "/audio/love-everyone/lovey.mp3" },
      { title: "Simulation Baptize", src: "/audio/love-everyone/simulation-baptize.mp3" },
      { title: "Ye vs. The People", src: "/audio/love-everyone/ye-vs-the-people.mp3" },
      { title: "Lift Yourself", src: "/audio/love-everyone/lift-yourself.mp3" },
      { title: "★ Ghost Town", src: "/audio/love-everyone/ghost-town.mp3", bonus: true },
      { title: "★ Brothers Forever", src: "/audio/love-everyone/brothers-forever.mp3", bonus: true },
    ],
  },
  {
    id: "war",
    title: "WAR",
    artist: "Kanye West",
    year: "2022",
    genre: "Art Pop / Alternative",
    cover: "/covers/war.gif",
    tracks: [
      { title: "It's Not Supposed To Be Perfect", src: "/audio/war/not-perfect.mp3" },
      { title: "For Once In My Life", src: "/audio/war/never-coming-back.mp3" },
      {
        title: "What I Would Had Said At Virgil's Funeral",
        src: "/audio/war/what-i-would-had-said-at-virgils-funeral.mp3",
      },
      { title: "Talking", src: "/audio/war/talking.mp3" },
      { title: "Quiet", src: "/audio/war/quiet.mp3" },
      { title: "Hold Up, Get Up", src: "/audio/war/hold-up-get-up.mp3" },
      { title: "Bobby Digital", src: "/audio/war/bobby-digital.mp3" },
      { title: "Through The High Wire", src: "/audio/war/high-wire.mp3" },
      { title: "Showtime", src: "/audio/war/showtime.mp3" },
      { title: "★ Things Change", src: "/audio/war/things-change.mp3", bonus: true },
      { title: "★ Came Back", src: "/audio/war/came-back.mp3", bonus: true },
      { title: "★ All Is Love", src: "/audio/war/all-in-love.mp3", bonus: true },
    ],
  },
  {
    id: "yebu",
    title: "YEBU",
    artist: "Kanye West",
    year: "2023",
    genre: "Hip-Hop / Soul",
    cover: "/covers/yebu-cover.jpg",
    tracks: [
      { title: "So Soon", src: "/audio/yebu/so-soon.mp3" },
      { title: "Unlock", src: "/audio/yebu/unlock.mp3" },
      { title: "Ceremony Freestyle", src: "/audio/yebu/ceremony-freestyle.mp3" },
      { title: "Hoodrat", src: "/audio/yebu/hoodrat.mp3" },
      { title: "Street Lights", src: "/audio/yebu/street-lights.mp3" },
      { title: "Someday We'll All Be Free", src: "/audio/yebu/someday-well-all-be-free.mp3" },
      { title: "Love Love Love", src: "/audio/yebu/love-love-love.mp3" },
      { title: "All In Love", src: "/audio/war/all-in-love.mp3" },
      { title: "Matthew", src: "/audio/yebu/matthew.mp3" },
      { title: "Big Boody (River)", src: "/audio/yebu/river.mp3" },
      { title: "★ Lucifer", src: "/audio/yebu/lucifer.mp3", bonus: true },
    ],
  },
  {
    id: "vultures2",
    title: "VULTURES 2",
    artist: "¥$, Kanye West & Ty Dolla $ign",
    year: "2024",
    genre: "Hip-Hop / Trap",
    cover: "/covers/vultures-2.jpg",
    tracks: [
      { title: "BELIEVER", src: "/audio/vultures-2/believer.mp3" },
      { title: "CAN U BE", src: "/audio/vultures-2/can-u-be-v2.mp3" },
      { title: "DRUNK", src: "/audio/vultures-2/drunk.mp3" },
      { title: "GUN TO MY HEAD", src: "/audio/vultures-2/gun-to-my-head.mp3" },
      { title: "TAKE OFF YOUR DRESS", src: "/audio/vultures-2/take-off-your-dress.mp3" },
      { title: "CASH COW", src: "/audio/vultures-2/cash-cow.mp3" },
      {
        title: "★ RIVER (August 3rd Version)",
        src: "/audio/vultures-2/river-v2.mp3",
        bonus: true,
      },
    ],
  },
  {
    id: "inaperfectworld",
    title: "In A Perfect World",
    artist: "Ye",
    year: "2025",
    genre: "Hip-Hop",
    cover: "/covers/cuck.jpg",
    tracks: [
      { title: "WW3", src: "/audio/in-a-perfect-world/ww3.mp3" },
      { title: "COSBY", src: "/audio/in-a-perfect-world/cosby.mp3" },
      { title: "DIDDY FREE", src: "/audio/in-a-perfect-world/diddy-free.mp3" },
      { title: "DIRTY MAGAZINES", src: "/audio/in-a-perfect-world/dirty-magazines.mp3" },
      { title: "JESUS", src: "/audio/in-a-perfect-world/jesus.mp3" },
      { title: "BIANCA", src: "/audio/in-a-perfect-world/bianca.mp3" },
      { title: "COUSINS", src: "/audio/in-a-perfect-world/cousins.mp3" },
      { title: "VIRGIL", src: "/audio/in-a-perfect-world/virgil.mp3" },
      { title: "UNCLE", src: "/audio/in-a-perfect-world/uncle.mp3" },
      { title: "FREE MY KIDS", src: "/audio/in-a-perfect-world/free-my-kids.mp3" },
      { title: "HEIL HITLER", src: "/audio/in-a-perfect-world/heil-hitler.mp3" },
      { title: "GAS CHAMBERS", src: "/audio/in-a-perfect-world/gas-chambers.mp3" },
      { title: "HITLER YE JESUS", src: "/audio/in-a-perfect-world/hitler-ye-jesus.mp3" },
      { title: "JARED", src: "/audio/in-a-perfect-world/jared.mp3" },
      { title: "NITROUS", src: "/audio/in-a-perfect-world/nitrous.mp3" },
      { title: "★ BIANCA V2", src: "/audio/in-a-perfect-world/bianca-v2.mp3", bonus: true },
    ],
  },
  {
    id: "bully",
    title: "BULLY",
    artist: "Ye",
    year: "2026",
    genre: "Hip-Hop",
    cover: "/covers/bully.jpg",
    tracks: [
      { title: "PREACHER MAN", src: "/audio/bully/preacher-man.mp3" },
      { title: "BEAUTY AND THE BEAST", src: "/audio/bully/beauty-and-the-beast.mp3" },
      { title: "DAMN", src: "/audio/bully/damn.mp3" },
      { title: "LAST BREATH", src: "/audio/bully/last-breath.mp3" },
      { title: "LOSING YOUR MIND", src: "/audio/bully/losing-your-mind.mp3" },
      { title: "HIGHS AND LOWS", src: "/audio/bully/highs-and-lows.mp3" },
      { title: "WHITE LINES", src: "/audio/bully/white-lines.mp3" },
      { title: "BULLY", src: "/audio/bully/bully.mp3" },
      { title: "CIRCLES", src: "/audio/bully/circles.mp3" },
      { title: "PEOPLE LIKE ME", src: "/audio/bully/people-like-me.mp3" },
      { title: "CAN'T HURRY LOVE", src: "/audio/bully/cant-hurry-love.mp3" },
      { title: "THIS ONE HERE", src: "/audio/bully/this-one-here.mp3" },
      { title: "★ MISSION CONTROL", src: "/audio/bully/mission-control.mp3", bonus: true },
    ],
  },
  {
    id: "godscountry",
    title: "God's Country",
    artist: "Kanye West",
    year: "2020",
    genre: "Hip-Hop / Gospel",
    cover: "/covers/gods-country.jpg",
    tracks: [
      { title: "Eternal Life", src: "/audio/gods-country/eternal-life.mp3" },
      { title: "12,000 Acres", src: "/audio/gods-country/12000-acres.mp3" },
      { title: "Future Bounce", src: "/audio/gods-country/future-bounce.mp3" },
      { title: "Lord I Need You", src: "/audio/gods-country/lord-i-need-you.mp3" },
      { title: "God's Country", src: "/audio/gods-country/gods-country.mp3" },
      { title: "Tulsa", src: "/audio/gods-country/tulsa.mp3" },
      { title: "Fighting Fires", src: "/audio/gods-country/fighting-fires.mp3" },
      { title: "Praise God", src: "/audio/gods-country/praise-god.mp3" },
      { title: "Keep My Spirit Alive", src: "/audio/gods-country/keep-my-spirit-alive.mp3" },
      { title: "Wash Us In The Blood", src: "/audio/gods-country/wash-us-in-the-blood.mp3" },
      { title: "★ Off The Grid", src: "/audio/gods-country/off-the-grid.mp3", bonus: true },
      { title: "★ Hear Our Prayers", src: "/audio/gods-country/hear-our-prayers.mp3", bonus: true },
    ],
  },
  {
    id: "jesusiskingdre",
    title: "JESUS IS KING: The Dr. Dre Version",
    artist: "Kanye West",
    year: "2020",
    genre: "Gospel / Hip-Hop",
    cover: "/covers/jikdre.jpg",
    tracks: [
      {
        title: "Intro / Every Hour / Selah",
        src: "/audio/jesus-is-king-dre/intro-every-hour-selah.mp3",
      },
      { title: "LA Monster", src: "/audio/jesus-is-king-dre/la-monster.mp3" },
      { title: "Water (Remix)", src: "/audio/jesus-is-king-dre/water-remix.mp3" },
      {
        title: "Closed On Sunday (Remix)",
        src: "/audio/jesus-is-king-dre/closed-on-sunday-remix.mp3",
      },
      { title: "On God (Remix)", src: "/audio/jesus-is-king-dre/on-god-remix.mp3" },
      { title: "Hands On (Remix)", src: "/audio/jesus-is-king-dre/hands-on-remix.mp3" },
      {
        title: "Everything We Need (Remix)",
        src: "/audio/jesus-is-king-dre/everything-we-need-remix.mp3",
      },
      { title: "Ashes", src: "/audio/jesus-is-king-dre/ashes.mp3" },
      { title: "God Is (Remix)", src: "/audio/jesus-is-king-dre/god-is-remix.mp3" },
      {
        title: "Use This Gospel (Remix)",
        src: "/audio/jesus-is-king-dre/use-this-gospel-remix.mp3",
      },
      { title: "Follow God", src: "/audio/jesus-is-king-dre/follow-god.mp3" },
      { title: "★ Glory", src: "/audio/jesus-is-king-dre/glory.mp3", bonus: true },
    ],
  },
  {
    id: "graduationdeluxe",
    title: "Graduation (Deluxe)",
    artist: "Kanye West",
    year: "2007",
    genre: "Hip-Hop",
    cover: "/covers/graduation.jpg",
    tracks: [
      { title: "Good Morning", src: "/audio/graduation-deluxe/good-morning.mp3" },
      { title: "Champion", src: "/audio/graduation-deluxe/champion.mp3" },
      { title: "Stronger", src: "/audio/graduation-deluxe/stronger.mp3" },
      { title: "I Wonder", src: "/audio/graduation-deluxe/i-wonder.mp3" },
      { title: "Good Life", src: "/audio/graduation-deluxe/good-life.mp3" },
      { title: "Can't Tell Me Nothing", src: "/audio/graduation-deluxe/cant-tell-me-nothing.mp3" },
      { title: "Barry Bonds", src: "/audio/graduation-deluxe/barry-bonds.mp3" },
      { title: "Drunk and Hot Girls", src: "/audio/graduation-deluxe/drunk-and-hot-girls.mp3" },
      { title: "Flashing Lights", src: "/audio/graduation-deluxe/flashing-lights.mp3" },
      { title: "Everything I Am", src: "/audio/graduation-deluxe/everything-i-am.mp3" },
      { title: "The Glory", src: "/audio/graduation-deluxe/the-glory.mp3" },
      { title: "Homecoming", src: "/audio/graduation-deluxe/homecoming.mp3" },
      { title: "Big Brother", src: "/audio/graduation-deluxe/big-brother.mp3" },
      { title: "Good Night", src: "/audio/graduation-deluxe/good-night.mp3" },
      {
        title: "★ Bittersweet Poetry",
        src: "/audio/graduation-deluxe/bittersweet-poetry.mp3",
        bonus: true,
      },
      { title: "★ Passenger", src: "/audio/graduation-deluxe/passenger.mp3", bonus: true },
      { title: "★ Building", src: "/audio/graduation-deluxe/building.mp3", bonus: true },
      { title: "★ Goodbye", src: "/audio/graduation-deluxe/goodbye.mp3", bonus: true },
    ],
  },
  {
    id: "record4hype",
    title: "record4hype.zip",
    artist: "Kanye West",
    year: "2010",
    genre: "Hip-Hop",
    cover: "/covers/record4hype.jpg",
    tracks: [
      { title: "Hell Of A Life", src: "/audio/record4hype/hell-of-a-life-hw.mp3" },
      { title: "Dark Fantasy", src: "/audio/record4hype/dark-fantasy-hw.mp3" },
      { title: "POWER", src: "/audio/record4hype/power-hw.mp3" },
      { title: "Chain Heavy", src: "/audio/record4hype/chain-heavy-hw.mp3" },
      { title: "Ghetto University", src: "/audio/record4hype/ghetto-university-hw.mp3" },
      { title: "That's My Bitch", src: "/audio/record4hype/thats-my-bitch-hw.mp3" },
      { title: "Runaway", src: "/audio/record4hype/runaway-hw.mp3" },
      { title: "Lost In The World", src: "/audio/record4hype/lost-in-the-world-hw.mp3" },
      { title: "Gorgeous", src: "/audio/record4hype/gorgeous-hw.mp3" },
      { title: "Monster", src: "/audio/record4hype/monster-hw.mp3" },
      { title: "Holding Me Back", src: "/audio/record4hype/holding-me-back-hw.mp3" },
      { title: "Devil In A New Dress", src: "/audio/record4hype/devil-in-a-new-dress-hw.mp3" },
      { title: "The Joy", src: "/audio/record4hype/the-joy-hw.mp3" },
      { title: "So Appalled", src: "/audio/record4hype/so-appalled-hw.mp3" },
      { title: "Blame Game", src: "/audio/record4hype/blame-game-hw.mp3" },
      { title: "★ Christian Dior Denim Flow", src: "/audio/record4hype/cddf.mp3", bonus: true },
      { title: "★ POWER (Remix)", src: "/audio/record4hype/power-remix.mp3", bonus: true },
      {
        title: "★ Sweat On My Face",
        src: "/audio/record4hype/sweat-on-my-face-hw.mp3",
        bonus: true,
      },
      { title: "★ See Me Now", src: "/audio/record4hype/see-me-now.mp3", bonus: true },
    ],
  },
  {
    id: "kanyessoulmixshow",
    title: "Kanye's Soul Mix Show",
    artist: "Kanye West",
    year: "2006",
    genre: "Soul / R&B",
    cover: "/covers/kanyessoulmixshow.jpg",
    tracks: [
      { title: "Intro", src: "/audio/kanyessoulmixshow/intro-show.mp3" },
      { title: "Wish You Were Here", src: "/audio/kanyessoulmixshow/wish-you-were-here.mp3" },
      {
        title: "Innocent 'Til Proven Guilty",
        src: "/audio/kanyessoulmixshow/innocent-til-proven-guilty.mp3",
      },
      { title: "Chicago", src: "/audio/kanyessoulmixshow/chicago.mp3" },
      { title: "Heart of the City", src: "/audio/kanyessoulmixshow/heart-of-the-city.mp3" },
      { title: "Common Man", src: "/audio/kanyessoulmixshow/common-man.mp3" },
      { title: "Strung Out", src: "/audio/kanyessoulmixshow/strung-out.mp3" },
      { title: "Wildflower", src: "/audio/kanyessoulmixshow/wildflower.mp3" },
      { title: "Ghetto Child", src: "/audio/kanyessoulmixshow/ghetto-child.mp3" },
      { title: "Peace and Love", src: "/audio/kanyessoulmixshow/peace-and-love.mp3" },
      { title: "Heavenly Dream", src: "/audio/kanyessoulmixshow/heavenly-dream.mp3" },
      {
        title: "I'll Erase Away Your Pain",
        src: "/audio/kanyessoulmixshow/ill-erase-away-your-pain.mp3",
      },
      { title: "A House Is Not a Home", src: "/audio/kanyessoulmixshow/a-house-is-not-a-home.mp3" },
      { title: "Through the Fire", src: "/audio/kanyessoulmixshow/through-the-fire.mp3" },
      { title: "Rosie", src: "/audio/kanyessoulmixshow/rosie.mp3" },
      { title: "My Funny Valentine", src: "/audio/kanyessoulmixshow/my-funny-valentine.mp3" },
      {
        title: "Home Is Where the Hatred Is",
        src: "/audio/kanyessoulmixshow/home-is-where-the-hatred-is.mp3",
      },
      { title: "Old Smokey", src: "/audio/kanyessoulmixshow/old-smokey.mp3" },
      {
        title: "Since You Came in My Life",
        src: "/audio/kanyessoulmixshow/since-you-came-in-my-life.mp3",
      },
      { title: "Move On Up", src: "/audio/kanyessoulmixshow/move-on-up.mp3" },
      { title: "It's Impossible", src: "/audio/kanyessoulmixshow/its-impossible.mp3" },
      { title: "Distant Lover", src: "/audio/kanyessoulmixshow/distant-lover.mp3" },
      { title: "Cause I Love You", src: "/audio/kanyessoulmixshow/cause-i-love-you.mp3" },
    ],
  },
  {
    id: "lateorchestration",
    title: "Late Orchestration",
    artist: "Kanye West",
    year: "2006",
    genre: "Hip-Hop / Live",
    cover: "/covers/lateorchestration.jpg",
    tracks: [
      { title: "Diamonds From Sierra Leone", src: "/audio/lateorchestration/dfsl.mp3" },
      { title: "Touch the Sky", src: "/audio/lateorchestration/touch-the-sky.mp3" },
      { title: "Crack Music", src: "/audio/lateorchestration/crack-music.mp3" },
      { title: "Drive Slow", src: "/audio/lateorchestration/drive-slow.mp3" },
      { title: "Through the Wire", src: "/audio/lateorchestration/through-the-wire.mp3" },
      { title: "The New Workout Plan", src: "/audio/lateorchestration/the-new-workout-plan.mp3" },
      { title: "Heard 'Em Say", src: "/audio/lateorchestration/heard-em-say.mp3" },
      { title: "All Falls Down", src: "/audio/lateorchestration/all-falls-down.mp3" },
      { title: "Bring Me Down", src: "/audio/lateorchestration/bring-me-down.mp3" },
      { title: "Gone", src: "/audio/lateorchestration/gone.mp3" },
      { title: "Late", src: "/audio/lateorchestration/late.mp3" },
      { title: "Jesus Walks", src: "/audio/lateorchestration/jesus-walks.mp3" },
      {
        title: "★ Gold Digger (AOL Sessions)",
        src: "/audio/lateorchestration/gold-digger-aol.mp3",
        bonus: true,
      },
    ],
  },
  {
    id: "cruelwinter",
    title: "Cruel Winter",
    artist: "Kanye West",
    year: "2014",
    genre: "Hip-Hop",
    cover: "/covers/cruel-winter.jpg",
    tracks: [
      { title: "Cruel Winter", src: "/audio/cruel-winter/cruel-winter.mp3" },
      { title: "Freestyle 4.1", src: "/audio/cruel-winter/freestyle-4-1.mp3" },
      { title: "Switch It Up", src: "/audio/cruel-winter/switch-it-up.mp3" },
      { title: "Regular", src: "/audio/cruel-winter/regular.mp3" },
      { title: "Freak On", src: "/audio/cruel-winter/freak-on.mp3" },
      { title: "Emotional", src: "/audio/cruel-winter/emotional.mp3" },
      { title: "Money Showers", src: "/audio/cruel-winter/money-showers.mp3" },
      { title: "Champions", src: "/audio/cruel-winter/champions-cw.mp3" },
      { title: "What A Year", src: "/audio/cruel-winter/what-a-year.mp3" },
      { title: "In Common", src: "/audio/cruel-winter/in-common.mp3" },
      { title: "Come Back To Me", src: "/audio/cruel-winter/come-back-to-me.mp3" },
      { title: "All I Know", src: "/audio/cruel-winter/all-i-know.mp3" },
      { title: "★ Love", src: "/audio/cruel-winter/love.mp3", bonus: true },
    ],
  },
] as const;

export const ALBUM_COUNT = albums.length; // 21

export type Album = (typeof albums)[number];
export type Track = Album["tracks"][number];

export type MusicState = {
  focused: number;
  album: number;
  track: number;
  playing: boolean;
  elapsed: number;
  volume: number;
  noSelection: boolean;
};

export type MusicAction =
  | { type: "focus"; index: number }
  | { type: "playAlbum"; index: number }
  | { type: "track"; album: number; track: number }
  | { type: "toggle" }
  | { type: "skip"; direction: number }
  | { type: "seek"; value: number }
  | { type: "volume"; value: number };

export const initialMusic: MusicState = {
  focused: 0,
  album: 0,
  track: 0,
  playing: false,
  elapsed: 0,
  volume: 0.7,
  noSelection: true, // no song selected on initial load
};

export function musicReducer(state: MusicState, action: MusicAction): MusicState {
  switch (action.type) {
    case "focus":
      return { ...state, focused: action.index };
    case "playAlbum":
      return { ...state, album: action.index, track: 0, playing: true, elapsed: 0, noSelection: false };
    case "track":
      return { ...state, album: action.album, track: action.track, playing: true, elapsed: 0, noSelection: false };
    case "toggle":
      return { ...state, playing: !state.playing };
    case "skip": {
      const count = albums[state.album]?.tracks.length ?? 1;
      return { ...state, track: (state.track + action.direction + count) % count, elapsed: 0 };
    }
    case "seek":
      return { ...state, elapsed: Math.max(0, action.value) };
    case "volume":
      return { ...state, volume: Math.max(0, Math.min(1, action.value)) };
  }
}

export function formatTime(seconds: number) {
  return `${Math.floor(seconds / 60)}:${String(Math.floor(seconds % 60)).padStart(2, "0")}`;
}
